namespace: kevinmgranger

name: crc

version: "0.0.3"

readme: README.md

authors:
  - Kevin M Granger <ansible@kevinmgranger.me>

description: set up and run an OpenShift Local cluster

license_file: COPYING

tags: ["codeready"]

build_ignore:
  - ".vscode"

repository: https://github.com/KevinMGranger/ansible-crc
issues: https://github.com/KevinMGranger/ansible-crc/issues
