---
- name: install
  include_tasks: installation.yml
  tags: [install]

- name: set up haproxy config
  copy:
    backup: yes
    src: haproxy.cfg
    dest: /etc/haproxy.cfg
  become: true
  tags: [remote-reachable]

# TODO: not enabling systemd service just yet because
# we'll probably want the `crc-runner`.
