---
- name: install
  include_tasks: installation.yml
  tags: [install]

- name: set up haproxy config
  copy:
    backup: yes
    src: haproxy.cfg
    dest: /etc/haproxy.cfg
  become: true
  tags: [remote-reachable]

- name: open firewalld service on given zone
  ansible.posix.firewalld:
    zone: "{{ firewall_zone }}"
    service: "{{ item }}"
    state: enabled
  loop:
    - kube-apiserver
    - http
  when: fireall_zone is defined
  tags: [remote-reachable]

# TODO: not enabling systemd service just yet because
# we'll probably want the `crc-runner`.
