---
crc_releases_url_base: https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/
latest_release_url_base: "{{ crc_releases_url_base }}/latest/"
installed_crc_path: "{{ansible_facts.env.HOME}}/.crc/bin/crc"
